main:
  project_name: predict_failures_in_university_subjects
  experiment_name: dev
  execute_steps:
    - download
    - preprocess
    - data_checks
    - segregation
    - random_forest
    - evaluate
  random_seed: 42
data:
  file_url: https://dados.ufrn.br/dataset/c8650d55-3c5a-4787-a126-d28a4ef902a6/resource/79071c21-e32c-438f-b930-d1b6ccc02ec2/download/matricula-componente-20171.csv
  enrollments_url: https://drive.google.com/uc?id=1YuHdRjQQRf_c9_5ME7AgeNQxZ9qt2wl7
  classes_url: https://drive.google.com/uc?id=1L6KQJVZ2hS6GfCHv3kjJcZxL9eRDB8n4
  reference_dataset: matriculas.csv:latest
  # Threshold for Kolomorov-Smirnov test
  ks_alpha: 0.1
  test_size: 0.3
  val_size: 0.3
  # Stratify according to the target when splitting the data
  # in train/test or in train/val
  stratify: reprovou
random_forest_pipeline:
  random_forest:
    criterion: "entropy"
    splitter: "best"
    max_depth: 13
  numerical_pipe:
    model: 0
  export_artifact: "model_export"
